#!/bin/bash
CMD=${2:-start}

SCRIPT_DIR=`dirname $LINK`
# by default will look in job sudirectory where syncd is located
JOBS_DIR=`$SCRIPT_DIR/jobs`
# otherwise you can comment above and uncomment below and provide an absolution path to your jobs directory
#JOBS_DIR="your/fav/abs/path"

FILES=$JOBS_DIR/$1/*
for file in $FILES
do
  name=${file##*/}
  base=${name%.conf}
  echo "Processing $base file..."
  syncd  $1/$base $CMD
done
exit
