#!/bin/bash
CMD=${2:-start}

if [ ${1:0:1} = / ]; then DIR=$1;
else
# if not absolute path then look in jobs sudirectory where syncd is located
SYNCD_DIR=`dirname $(readlink -f $0)`
DIR=$SYNCD_DIR/jobs/$1
fi

echo $DIR
# only looks for conf files does not recurse subdirectories
GLOB=$DIR/*.conf
echo $GLOB
if find $GLOB -quit &> /dev/null; then
for file in $GLOB
do
  name=${file##*/}
  conf=${name%.conf}
  echo "Processing configuration file $conf"
  syncd  $DIR/$conf $CMD
done
else echo 'No configuration files found in' $DIR
fi
exit
