#!/bin/bash
#------------------------------------------------------------
# initd script for running services without start-stop-daemon
# (c) Wolfgang Ziegler, nuppla@zites.net, drunomics GmbH
#------------------------------------------------------------

# Find config file

CONF_FILE="$1.conf"
# TODO read config files from a directory and start a daemon for each instead of in a directory above.

while [ ! -e $CONF_FILE ]; do
  if [ $PWD = "/" ]; then
    echo "Unable to find syncd configuration file \"$CONF_FILE\"."
    exit 1
  else
    cd ..
  fi
done

SYNCD_CONFIG_DIR=$PWD
SCRIPT=`readlink -f $0`
DAEMON_NAME=syncd
LINK=`readlink -f $0`
SCRIPT_DIR=`dirname $LINK`

# source the config file here
. $CONF_FILE

if [ -z "$SSH_HOST" ]; then TARGET=$TARGET_DIR; else TARGET=$SSH_USER@$SSH_HOST:$TARGET_DIR; fi

#echo target is: $TARGET

# COMMAND="rsync $RSYNC_OPTIONS --exclude=$RSYNC_EXCLUDE --delete $WATCH_DIR/ $SSH_USER@$SSH_HOST:$REMOTE_TARGET_DIR"
COMMAND="rsync $RSYNC_OPTIONS --exclude=$RSYNC_EXCLUDE $WATCH_DIR/ $TARGET"

# echo $COMMAND


case $2 in
    start)
      if [ -e ${PIDFILE} ] && ( ps -p `cat $PIDFILE` > /dev/null ); then
        echo "$DAEMON_NAME is already running."
        exit 1;
      fi
      export WATCH_EXCLUDE
      export WATCH_VERBOSE
      export WATCH_DIR
      $SCRIPT_DIR/watch.sh $COMMAND >> $LOGFILE &
      echo "$!" > $PIDFILE
      echo "Starting $DAEMON_NAME..."
    ;;

    stop)
      if [ ! -e ${PIDFILE} ] || ( ! ps -p `cat $PIDFILE` > /dev/null ); then
        echo "$DAEMON_NAME is not running."
        exit 1;
      fi

      echo "Stopping $DAEMON_NAME..."
      PID=`cat $PIDFILE`
      CHILD_PIDS=$(pgrep -P $PID);
      kill $PID 2> /dev/null || echo Killing process failed, not running?
      # Wait half a second and Kill child PIDs to be sure they are gone.
      sleep 0.5
      kill $CHILD_PIDS 2> /dev/null
      rm $PIDFILE
    ;;
    restart)
      $SCRIPT $1 stop
      $SCRIPT $1 start
    ;;

    status)
      if [ -e ${PIDFILE} ] && ( ps -p `cat $PIDFILE` > /dev/null ); then
          echo "$DAEMON_NAME is running."
      else
          echo "$DAEMON_NAME is not running."
      fi
    ;;

    run)
      echo $COMMAND
	read -p "Ok to run this command? [yn]" ans
	if [ $ans = y ] ; then
	      $COMMAND && echo Done
	fi
    ;;

    log)
      tail -f $LOGFILE
    ;;

    *)
      echo "Usage: $0 {start|stop|restart|status|run|log}"
      exit 3
    ;;
esac
